### ISSUE TITLE
pom.xml/mvn based projects need to create ~/.m2/settings.xml BEFORE travis install block

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/travis-build-configuration#10]
current situation (`~/.m2/settings.xml` created in **before_script:** ):

``` yaml

before_script:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml

script: 'mvn clean install'
```

should be (`~/.m2/settings.xml` created in **before_install:** ):

``` yaml

before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml

script: 'mvn clean install'
```

This is required in order for the `~/.m2/settings.xml` file be created and control the maven behavior for resolving remote repos and dependencies; otherwise maven will start automatically processing your `pom.xml` file in the **default** `install:` step and most likely that will fail.
- [x] upgrade one-by-one **all** ALA `pom.xml`/`mvn` based projects `.travis.yml` files
- [x] update the [travis pom.xml based project template](https://github.com/AtlasOfLivingAustralia/travis-build-configuration/blob/master/templates/travis-java_template.yml)
